flesh out daily run yml and remove duplicate import statement in main

diff --git a/.github/workflows/daily-run.yml b/.github/workflows/daily-run.yml
--- a/.github/workflows/daily-run.yml
+++ b/.github/workflows/daily-run.yml
@@ -1,23 +1,61 @@
-name: Python application
+name: Daily Run
 
 on:
   push:
     - cron: '0 0 7 * * ?' # Runs every day at 7am
 
-permissions:
-  contents: read
+env:
+  api_key: ${{ secrets.API_KEY }}
+  cap_api_key: ${{ secrets.CAP_API_KEY }}
+  snow_user: ${{ secrets.SNOW_USER }}
+  snow_password: ${{ secrets.SNOW_PASSWORD }}
+  snow_account: ${{ secrets.SNOW_ACCOUNT }}
+  snow_warehouse: ${{ secrets.SNOW_WAREHOUSE }}
+  snow_database: ${{ secrets.SNOW_DATABASE }}
+  snow_schema: ${{ secrets.SNOW_SCHEMA }}
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
     steps:
+    - name: Checkout Code
     - uses: actions/checkout@v3
+
+    - name: Cache dependencies
+      uses: actions/cache@v3
+      with:
+        path: |
+          ~/.cache/pip
+          /opt/hostedtoolcache/Python
+        key: ${{ runner.os }}-dependencies-${{ hashFiles('requirements.txt') }}
+        restore-keys: |
+          ${{ runner.os }}-dependencies-
+
     - name: Set up Python 3.10
+      if: steps.cache-dependencies.outputs.cache-hit != 'true'
       uses: actions/setup-python@v3
       with:
-        python-version: "3.10"
+        python-version: '3.10'
+
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
+        python -m pip install -r requirements.txt
+
+    - name: Run Python Scripts
+      run: |
+        python main.py
+
+    - name: Commit files
+      run: |
+        git config --local user.email "manokes93@gmail.com"
+        git config --local user.name "Michael Nokes"
+        git add -A
+        git diff-index --quiet HEAD failures.log || (git commit failures.log -m "updated failures log")
+
+    - name: Push changes
+      uses: ad-m/github-push-action@v0.6.0
+      with:
+        github_token: ${{ secrets.GITHUB_TOKEN }}
+        branch: main
